/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/sprints": {
    /** Get all sprints */
    get: {
      parameters: {
        query: {
          project_id: components["parameters"]["ProjectId"];
        };
      };
      responses: {
        /** @description An array of sprints in the project */
        200: {
          content: {
            "application/json": components["schemas"]["Sprint"][];
          };
        };
      };
    };
    /** Create a sprint */
    post: {
      parameters: {
        query: {
          project_id: components["parameters"]["ProjectId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Sprint"];
        };
      };
      responses: {
        /** @description Created */
        200: {
          content: never;
        };
      };
    };
  };
  "/sprints/{id}": {
    /** Get sprint */
    get: {
      parameters: {
        query: {
          project_id: components["parameters"]["ProjectId"];
        };
        path: {
          id: components["parameters"]["Id"];
        };
      };
      responses: {
        /** @description A sprint */
        200: {
          content: {
            "application/json": components["schemas"]["Sprint"][];
          };
        };
      };
    };
    /** Update a sprint */
    put: {
      parameters: {
        query: {
          project_id: components["parameters"]["ProjectId"];
        };
        path: {
          id: components["parameters"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Sprint"];
        };
      };
      responses: {
        /** @description Updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete a sprint */
    delete: {
      parameters: {
        query: {
          project_id: components["parameters"]["ProjectId"];
        };
        path: {
          id: components["parameters"]["Id"];
        };
      };
      responses: {
        /** @description Deleted */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Sprint: {
      id: number;
      title: string;
      description?: string | null;
      startAt?: string;
      endAt?: string;
      creatorId?: number;
      projectId?: number;
      createdAt?: string;
      updatedAt?: string;
    };
  };
  responses: never;
  parameters: {
    Id: number;
    ProjectId: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
